# Generated by Django 2.0.1 on 2020-04-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Basic', models.CharField(max_length=100)),
                ('Electrical', models.CharField(max_length=100)),
                ('Mechanical', models.CharField(max_length=100)),
                ('Installation', models.CharField(max_length=100)),
                ('Water', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField()),
                ('Basic1', models.BooleanField(default=False)),
                ('Electrical1', models.BooleanField(default=False)),
                ('Mechanical1', models.BooleanField(default=False)),
                ('Installation1', models.BooleanField(default=False)),
                ('Water1', models.BooleanField(default=False)),
            ],
        ),
    ]
