# Generated by Django 2.0.1 on 2020-04-26 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='Basic1',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='option',
            name='Electrical1',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='option',
            name='Installation1',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='option',
            name='Mechanical1',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='option',
            name='Water1',
            field=models.NullBooleanField(),
        ),
    ]
