# Generated by Django 2.0.1 on 2020-04-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0003_auto_20200426_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='Basic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Electrical',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Installation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Mechanical',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Water',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
